/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantSelectorRouteImport } from './routes/restaurant/selector'
import { Route as RestaurantCreateRouteImport } from './routes/restaurant/create'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as RestaurantManageRestaurantIdRouteImport } from './routes/restaurant/manage/$restaurantId'
import { Route as RestaurantAccountSettingsRouteImport } from './routes/restaurant/account/settings'
import { Route as RestaurantAccountSecurityRouteImport } from './routes/restaurant/account/security'
import { Route as RestaurantAccountRestaurantsRouteImport } from './routes/restaurant/account/restaurants'
import { Route as RestaurantManageRestaurantIdIndexRouteImport } from './routes/restaurant/manage/$restaurantId/index'
import { Route as RestaurantManageRestaurantIdMenuRouteImport } from './routes/restaurant/manage/$restaurantId/menu'
import { Route as RestaurantManageRestaurantIdStoreIndexRouteImport } from './routes/restaurant/manage/$restaurantId/store/index'
import { Route as RestaurantManageRestaurantIdStoreSeoRouteImport } from './routes/restaurant/manage/$restaurantId/store/seo'
import { Route as RestaurantManageRestaurantIdStoreLocationRouteImport } from './routes/restaurant/manage/$restaurantId/store/location'
import { Route as RestaurantManageRestaurantIdStoreDetailsRouteImport } from './routes/restaurant/manage/$restaurantId/store/details'
import { Route as RestaurantManageRestaurantIdStoreDeliveryRouteImport } from './routes/restaurant/manage/$restaurantId/store/delivery'
import { Route as RestaurantManageRestaurantIdMenuEditRouteImport } from './routes/restaurant/manage/$restaurantId/menu/edit'
import { Route as RestaurantManageRestaurantIdMenuBillingRouteImport } from './routes/restaurant/manage/$restaurantId/menu/billing'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSelectorRoute = RestaurantSelectorRouteImport.update({
  id: '/selector',
  path: '/selector',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantCreateRoute = RestaurantCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RestaurantRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const RestaurantManageRestaurantIdRoute =
  RestaurantManageRestaurantIdRouteImport.update({
    id: '/manage/$restaurantId',
    path: '/manage/$restaurantId',
    getParentRoute: () => RestaurantRoute,
  } as any)
const RestaurantAccountSettingsRoute =
  RestaurantAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => RestaurantRoute,
  } as any)
const RestaurantAccountSecurityRoute =
  RestaurantAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => RestaurantRoute,
  } as any)
const RestaurantAccountRestaurantsRoute =
  RestaurantAccountRestaurantsRouteImport.update({
    id: '/account/restaurants',
    path: '/account/restaurants',
    getParentRoute: () => RestaurantRoute,
  } as any)
const RestaurantManageRestaurantIdIndexRoute =
  RestaurantManageRestaurantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdMenuRoute =
  RestaurantManageRestaurantIdMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdStoreIndexRoute =
  RestaurantManageRestaurantIdStoreIndexRouteImport.update({
    id: '/store/',
    path: '/store/',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdStoreSeoRoute =
  RestaurantManageRestaurantIdStoreSeoRouteImport.update({
    id: '/store/seo',
    path: '/store/seo',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdStoreLocationRoute =
  RestaurantManageRestaurantIdStoreLocationRouteImport.update({
    id: '/store/location',
    path: '/store/location',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdStoreDetailsRoute =
  RestaurantManageRestaurantIdStoreDetailsRouteImport.update({
    id: '/store/details',
    path: '/store/details',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdStoreDeliveryRoute =
  RestaurantManageRestaurantIdStoreDeliveryRouteImport.update({
    id: '/store/delivery',
    path: '/store/delivery',
    getParentRoute: () => RestaurantManageRestaurantIdRoute,
  } as any)
const RestaurantManageRestaurantIdMenuEditRoute =
  RestaurantManageRestaurantIdMenuEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RestaurantManageRestaurantIdMenuRoute,
  } as any)
const RestaurantManageRestaurantIdMenuBillingRoute =
  RestaurantManageRestaurantIdMenuBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => RestaurantManageRestaurantIdMenuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/restaurant': typeof RestaurantRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/restaurant/create': typeof RestaurantCreateRoute
  '/restaurant/selector': typeof RestaurantSelectorRoute
  '/restaurant/account/restaurants': typeof RestaurantAccountRestaurantsRoute
  '/restaurant/account/security': typeof RestaurantAccountSecurityRoute
  '/restaurant/account/settings': typeof RestaurantAccountSettingsRoute
  '/restaurant/manage/$restaurantId': typeof RestaurantManageRestaurantIdRouteWithChildren
  '/restaurant/manage/$restaurantId/menu': typeof RestaurantManageRestaurantIdMenuRouteWithChildren
  '/restaurant/manage/$restaurantId/': typeof RestaurantManageRestaurantIdIndexRoute
  '/restaurant/manage/$restaurantId/menu/billing': typeof RestaurantManageRestaurantIdMenuBillingRoute
  '/restaurant/manage/$restaurantId/menu/edit': typeof RestaurantManageRestaurantIdMenuEditRoute
  '/restaurant/manage/$restaurantId/store/delivery': typeof RestaurantManageRestaurantIdStoreDeliveryRoute
  '/restaurant/manage/$restaurantId/store/details': typeof RestaurantManageRestaurantIdStoreDetailsRoute
  '/restaurant/manage/$restaurantId/store/location': typeof RestaurantManageRestaurantIdStoreLocationRoute
  '/restaurant/manage/$restaurantId/store/seo': typeof RestaurantManageRestaurantIdStoreSeoRoute
  '/restaurant/manage/$restaurantId/store': typeof RestaurantManageRestaurantIdStoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/restaurant': typeof RestaurantRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/restaurant/create': typeof RestaurantCreateRoute
  '/restaurant/selector': typeof RestaurantSelectorRoute
  '/restaurant/account/restaurants': typeof RestaurantAccountRestaurantsRoute
  '/restaurant/account/security': typeof RestaurantAccountSecurityRoute
  '/restaurant/account/settings': typeof RestaurantAccountSettingsRoute
  '/restaurant/manage/$restaurantId/menu': typeof RestaurantManageRestaurantIdMenuRouteWithChildren
  '/restaurant/manage/$restaurantId': typeof RestaurantManageRestaurantIdIndexRoute
  '/restaurant/manage/$restaurantId/menu/billing': typeof RestaurantManageRestaurantIdMenuBillingRoute
  '/restaurant/manage/$restaurantId/menu/edit': typeof RestaurantManageRestaurantIdMenuEditRoute
  '/restaurant/manage/$restaurantId/store/delivery': typeof RestaurantManageRestaurantIdStoreDeliveryRoute
  '/restaurant/manage/$restaurantId/store/details': typeof RestaurantManageRestaurantIdStoreDetailsRoute
  '/restaurant/manage/$restaurantId/store/location': typeof RestaurantManageRestaurantIdStoreLocationRoute
  '/restaurant/manage/$restaurantId/store/seo': typeof RestaurantManageRestaurantIdStoreSeoRoute
  '/restaurant/manage/$restaurantId/store': typeof RestaurantManageRestaurantIdStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/restaurant': typeof RestaurantRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/restaurant/create': typeof RestaurantCreateRoute
  '/restaurant/selector': typeof RestaurantSelectorRoute
  '/restaurant/account/restaurants': typeof RestaurantAccountRestaurantsRoute
  '/restaurant/account/security': typeof RestaurantAccountSecurityRoute
  '/restaurant/account/settings': typeof RestaurantAccountSettingsRoute
  '/restaurant/manage/$restaurantId': typeof RestaurantManageRestaurantIdRouteWithChildren
  '/restaurant/manage/$restaurantId/menu': typeof RestaurantManageRestaurantIdMenuRouteWithChildren
  '/restaurant/manage/$restaurantId/': typeof RestaurantManageRestaurantIdIndexRoute
  '/restaurant/manage/$restaurantId/menu/billing': typeof RestaurantManageRestaurantIdMenuBillingRoute
  '/restaurant/manage/$restaurantId/menu/edit': typeof RestaurantManageRestaurantIdMenuEditRoute
  '/restaurant/manage/$restaurantId/store/delivery': typeof RestaurantManageRestaurantIdStoreDeliveryRoute
  '/restaurant/manage/$restaurantId/store/details': typeof RestaurantManageRestaurantIdStoreDetailsRoute
  '/restaurant/manage/$restaurantId/store/location': typeof RestaurantManageRestaurantIdStoreLocationRoute
  '/restaurant/manage/$restaurantId/store/seo': typeof RestaurantManageRestaurantIdStoreSeoRoute
  '/restaurant/manage/$restaurantId/store/': typeof RestaurantManageRestaurantIdStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/restaurant'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/restaurant/create'
    | '/restaurant/selector'
    | '/restaurant/account/restaurants'
    | '/restaurant/account/security'
    | '/restaurant/account/settings'
    | '/restaurant/manage/$restaurantId'
    | '/restaurant/manage/$restaurantId/menu'
    | '/restaurant/manage/$restaurantId/'
    | '/restaurant/manage/$restaurantId/menu/billing'
    | '/restaurant/manage/$restaurantId/menu/edit'
    | '/restaurant/manage/$restaurantId/store/delivery'
    | '/restaurant/manage/$restaurantId/store/details'
    | '/restaurant/manage/$restaurantId/store/location'
    | '/restaurant/manage/$restaurantId/store/seo'
    | '/restaurant/manage/$restaurantId/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/restaurant'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/restaurant/create'
    | '/restaurant/selector'
    | '/restaurant/account/restaurants'
    | '/restaurant/account/security'
    | '/restaurant/account/settings'
    | '/restaurant/manage/$restaurantId/menu'
    | '/restaurant/manage/$restaurantId'
    | '/restaurant/manage/$restaurantId/menu/billing'
    | '/restaurant/manage/$restaurantId/menu/edit'
    | '/restaurant/manage/$restaurantId/store/delivery'
    | '/restaurant/manage/$restaurantId/store/details'
    | '/restaurant/manage/$restaurantId/store/location'
    | '/restaurant/manage/$restaurantId/store/seo'
    | '/restaurant/manage/$restaurantId/store'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/restaurant'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/restaurant/create'
    | '/restaurant/selector'
    | '/restaurant/account/restaurants'
    | '/restaurant/account/security'
    | '/restaurant/account/settings'
    | '/restaurant/manage/$restaurantId'
    | '/restaurant/manage/$restaurantId/menu'
    | '/restaurant/manage/$restaurantId/'
    | '/restaurant/manage/$restaurantId/menu/billing'
    | '/restaurant/manage/$restaurantId/menu/edit'
    | '/restaurant/manage/$restaurantId/store/delivery'
    | '/restaurant/manage/$restaurantId/store/details'
    | '/restaurant/manage/$restaurantId/store/location'
    | '/restaurant/manage/$restaurantId/store/seo'
    | '/restaurant/manage/$restaurantId/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  RestaurantRoute: typeof RestaurantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/selector': {
      id: '/restaurant/selector'
      path: '/selector'
      fullPath: '/restaurant/selector'
      preLoaderRoute: typeof RestaurantSelectorRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/create': {
      id: '/restaurant/create'
      path: '/create'
      fullPath: '/restaurant/create'
      preLoaderRoute: typeof RestaurantCreateRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/restaurant/manage/$restaurantId': {
      id: '/restaurant/manage/$restaurantId'
      path: '/manage/$restaurantId'
      fullPath: '/restaurant/manage/$restaurantId'
      preLoaderRoute: typeof RestaurantManageRestaurantIdRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/account/settings': {
      id: '/restaurant/account/settings'
      path: '/account/settings'
      fullPath: '/restaurant/account/settings'
      preLoaderRoute: typeof RestaurantAccountSettingsRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/account/security': {
      id: '/restaurant/account/security'
      path: '/account/security'
      fullPath: '/restaurant/account/security'
      preLoaderRoute: typeof RestaurantAccountSecurityRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/account/restaurants': {
      id: '/restaurant/account/restaurants'
      path: '/account/restaurants'
      fullPath: '/restaurant/account/restaurants'
      preLoaderRoute: typeof RestaurantAccountRestaurantsRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/manage/$restaurantId/': {
      id: '/restaurant/manage/$restaurantId/'
      path: '/'
      fullPath: '/restaurant/manage/$restaurantId/'
      preLoaderRoute: typeof RestaurantManageRestaurantIdIndexRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/menu': {
      id: '/restaurant/manage/$restaurantId/menu'
      path: '/menu'
      fullPath: '/restaurant/manage/$restaurantId/menu'
      preLoaderRoute: typeof RestaurantManageRestaurantIdMenuRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/store/': {
      id: '/restaurant/manage/$restaurantId/store/'
      path: '/store'
      fullPath: '/restaurant/manage/$restaurantId/store'
      preLoaderRoute: typeof RestaurantManageRestaurantIdStoreIndexRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/store/seo': {
      id: '/restaurant/manage/$restaurantId/store/seo'
      path: '/store/seo'
      fullPath: '/restaurant/manage/$restaurantId/store/seo'
      preLoaderRoute: typeof RestaurantManageRestaurantIdStoreSeoRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/store/location': {
      id: '/restaurant/manage/$restaurantId/store/location'
      path: '/store/location'
      fullPath: '/restaurant/manage/$restaurantId/store/location'
      preLoaderRoute: typeof RestaurantManageRestaurantIdStoreLocationRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/store/details': {
      id: '/restaurant/manage/$restaurantId/store/details'
      path: '/store/details'
      fullPath: '/restaurant/manage/$restaurantId/store/details'
      preLoaderRoute: typeof RestaurantManageRestaurantIdStoreDetailsRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/store/delivery': {
      id: '/restaurant/manage/$restaurantId/store/delivery'
      path: '/store/delivery'
      fullPath: '/restaurant/manage/$restaurantId/store/delivery'
      preLoaderRoute: typeof RestaurantManageRestaurantIdStoreDeliveryRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdRoute
    }
    '/restaurant/manage/$restaurantId/menu/edit': {
      id: '/restaurant/manage/$restaurantId/menu/edit'
      path: '/edit'
      fullPath: '/restaurant/manage/$restaurantId/menu/edit'
      preLoaderRoute: typeof RestaurantManageRestaurantIdMenuEditRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdMenuRoute
    }
    '/restaurant/manage/$restaurantId/menu/billing': {
      id: '/restaurant/manage/$restaurantId/menu/billing'
      path: '/billing'
      fullPath: '/restaurant/manage/$restaurantId/menu/billing'
      preLoaderRoute: typeof RestaurantManageRestaurantIdMenuBillingRouteImport
      parentRoute: typeof RestaurantManageRestaurantIdMenuRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RestaurantManageRestaurantIdMenuRouteChildren {
  RestaurantManageRestaurantIdMenuBillingRoute: typeof RestaurantManageRestaurantIdMenuBillingRoute
  RestaurantManageRestaurantIdMenuEditRoute: typeof RestaurantManageRestaurantIdMenuEditRoute
}

const RestaurantManageRestaurantIdMenuRouteChildren: RestaurantManageRestaurantIdMenuRouteChildren =
  {
    RestaurantManageRestaurantIdMenuBillingRoute:
      RestaurantManageRestaurantIdMenuBillingRoute,
    RestaurantManageRestaurantIdMenuEditRoute:
      RestaurantManageRestaurantIdMenuEditRoute,
  }

const RestaurantManageRestaurantIdMenuRouteWithChildren =
  RestaurantManageRestaurantIdMenuRoute._addFileChildren(
    RestaurantManageRestaurantIdMenuRouteChildren,
  )

interface RestaurantManageRestaurantIdRouteChildren {
  RestaurantManageRestaurantIdMenuRoute: typeof RestaurantManageRestaurantIdMenuRouteWithChildren
  RestaurantManageRestaurantIdIndexRoute: typeof RestaurantManageRestaurantIdIndexRoute
  RestaurantManageRestaurantIdStoreDeliveryRoute: typeof RestaurantManageRestaurantIdStoreDeliveryRoute
  RestaurantManageRestaurantIdStoreDetailsRoute: typeof RestaurantManageRestaurantIdStoreDetailsRoute
  RestaurantManageRestaurantIdStoreLocationRoute: typeof RestaurantManageRestaurantIdStoreLocationRoute
  RestaurantManageRestaurantIdStoreSeoRoute: typeof RestaurantManageRestaurantIdStoreSeoRoute
  RestaurantManageRestaurantIdStoreIndexRoute: typeof RestaurantManageRestaurantIdStoreIndexRoute
}

const RestaurantManageRestaurantIdRouteChildren: RestaurantManageRestaurantIdRouteChildren =
  {
    RestaurantManageRestaurantIdMenuRoute:
      RestaurantManageRestaurantIdMenuRouteWithChildren,
    RestaurantManageRestaurantIdIndexRoute:
      RestaurantManageRestaurantIdIndexRoute,
    RestaurantManageRestaurantIdStoreDeliveryRoute:
      RestaurantManageRestaurantIdStoreDeliveryRoute,
    RestaurantManageRestaurantIdStoreDetailsRoute:
      RestaurantManageRestaurantIdStoreDetailsRoute,
    RestaurantManageRestaurantIdStoreLocationRoute:
      RestaurantManageRestaurantIdStoreLocationRoute,
    RestaurantManageRestaurantIdStoreSeoRoute:
      RestaurantManageRestaurantIdStoreSeoRoute,
    RestaurantManageRestaurantIdStoreIndexRoute:
      RestaurantManageRestaurantIdStoreIndexRoute,
  }

const RestaurantManageRestaurantIdRouteWithChildren =
  RestaurantManageRestaurantIdRoute._addFileChildren(
    RestaurantManageRestaurantIdRouteChildren,
  )

interface RestaurantRouteChildren {
  RestaurantCreateRoute: typeof RestaurantCreateRoute
  RestaurantSelectorRoute: typeof RestaurantSelectorRoute
  RestaurantAccountRestaurantsRoute: typeof RestaurantAccountRestaurantsRoute
  RestaurantAccountSecurityRoute: typeof RestaurantAccountSecurityRoute
  RestaurantAccountSettingsRoute: typeof RestaurantAccountSettingsRoute
  RestaurantManageRestaurantIdRoute: typeof RestaurantManageRestaurantIdRouteWithChildren
}

const RestaurantRouteChildren: RestaurantRouteChildren = {
  RestaurantCreateRoute: RestaurantCreateRoute,
  RestaurantSelectorRoute: RestaurantSelectorRoute,
  RestaurantAccountRestaurantsRoute: RestaurantAccountRestaurantsRoute,
  RestaurantAccountSecurityRoute: RestaurantAccountSecurityRoute,
  RestaurantAccountSettingsRoute: RestaurantAccountSettingsRoute,
  RestaurantManageRestaurantIdRoute:
    RestaurantManageRestaurantIdRouteWithChildren,
}

const RestaurantRouteWithChildren = RestaurantRoute._addFileChildren(
  RestaurantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  RestaurantRoute: RestaurantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
