/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantRestaurantIdRouteImport } from './routes/restaurant/$restaurantId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as RestaurantRestaurantIdIndexRouteImport } from './routes/restaurant/$restaurantId/index'
import { Route as RestaurantRestaurantIdMenuRouteImport } from './routes/restaurant/$restaurantId/menu'
import { Route as RestaurantRestaurantIdUsersCreateRouteImport } from './routes/restaurant/$restaurantId/users/create'
import { Route as RestaurantRestaurantIdUsersActiveRouteImport } from './routes/restaurant/$restaurantId/users/active'
import { Route as RestaurantRestaurantIdMenuEditRouteImport } from './routes/restaurant/$restaurantId/menu/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRestaurantIdRoute = RestaurantRestaurantIdRouteImport.update({
  id: '/restaurant/$restaurantId',
  path: '/restaurant/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const RestaurantRestaurantIdIndexRoute =
  RestaurantRestaurantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantRestaurantIdRoute,
  } as any)
const RestaurantRestaurantIdMenuRoute =
  RestaurantRestaurantIdMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => RestaurantRestaurantIdRoute,
  } as any)
const RestaurantRestaurantIdUsersCreateRoute =
  RestaurantRestaurantIdUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => RestaurantRestaurantIdRoute,
  } as any)
const RestaurantRestaurantIdUsersActiveRoute =
  RestaurantRestaurantIdUsersActiveRouteImport.update({
    id: '/users/active',
    path: '/users/active',
    getParentRoute: () => RestaurantRestaurantIdRoute,
  } as any)
const RestaurantRestaurantIdMenuEditRoute =
  RestaurantRestaurantIdMenuEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RestaurantRestaurantIdMenuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRouteWithChildren
  '/restaurant/$restaurantId/menu': typeof RestaurantRestaurantIdMenuRouteWithChildren
  '/restaurant/$restaurantId/': typeof RestaurantRestaurantIdIndexRoute
  '/restaurant/$restaurantId/menu/edit': typeof RestaurantRestaurantIdMenuEditRoute
  '/restaurant/$restaurantId/users/active': typeof RestaurantRestaurantIdUsersActiveRoute
  '/restaurant/$restaurantId/users/create': typeof RestaurantRestaurantIdUsersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/restaurant/$restaurantId/menu': typeof RestaurantRestaurantIdMenuRouteWithChildren
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdIndexRoute
  '/restaurant/$restaurantId/menu/edit': typeof RestaurantRestaurantIdMenuEditRoute
  '/restaurant/$restaurantId/users/active': typeof RestaurantRestaurantIdUsersActiveRoute
  '/restaurant/$restaurantId/users/create': typeof RestaurantRestaurantIdUsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRouteWithChildren
  '/restaurant/$restaurantId/menu': typeof RestaurantRestaurantIdMenuRouteWithChildren
  '/restaurant/$restaurantId/': typeof RestaurantRestaurantIdIndexRoute
  '/restaurant/$restaurantId/menu/edit': typeof RestaurantRestaurantIdMenuEditRoute
  '/restaurant/$restaurantId/users/active': typeof RestaurantRestaurantIdUsersActiveRoute
  '/restaurant/$restaurantId/users/create': typeof RestaurantRestaurantIdUsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/restaurant/$restaurantId'
    | '/restaurant/$restaurantId/menu'
    | '/restaurant/$restaurantId/'
    | '/restaurant/$restaurantId/menu/edit'
    | '/restaurant/$restaurantId/users/active'
    | '/restaurant/$restaurantId/users/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/restaurant/$restaurantId/menu'
    | '/restaurant/$restaurantId'
    | '/restaurant/$restaurantId/menu/edit'
    | '/restaurant/$restaurantId/users/active'
    | '/restaurant/$restaurantId/users/create'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/restaurant/$restaurantId'
    | '/restaurant/$restaurantId/menu'
    | '/restaurant/$restaurantId/'
    | '/restaurant/$restaurantId/menu/edit'
    | '/restaurant/$restaurantId/users/active'
    | '/restaurant/$restaurantId/users/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  RestaurantRestaurantIdRoute: typeof RestaurantRestaurantIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$restaurantId': {
      id: '/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/restaurant/$restaurantId'
      preLoaderRoute: typeof RestaurantRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/restaurant/$restaurantId/': {
      id: '/restaurant/$restaurantId/'
      path: '/'
      fullPath: '/restaurant/$restaurantId/'
      preLoaderRoute: typeof RestaurantRestaurantIdIndexRouteImport
      parentRoute: typeof RestaurantRestaurantIdRoute
    }
    '/restaurant/$restaurantId/menu': {
      id: '/restaurant/$restaurantId/menu'
      path: '/menu'
      fullPath: '/restaurant/$restaurantId/menu'
      preLoaderRoute: typeof RestaurantRestaurantIdMenuRouteImport
      parentRoute: typeof RestaurantRestaurantIdRoute
    }
    '/restaurant/$restaurantId/users/create': {
      id: '/restaurant/$restaurantId/users/create'
      path: '/users/create'
      fullPath: '/restaurant/$restaurantId/users/create'
      preLoaderRoute: typeof RestaurantRestaurantIdUsersCreateRouteImport
      parentRoute: typeof RestaurantRestaurantIdRoute
    }
    '/restaurant/$restaurantId/users/active': {
      id: '/restaurant/$restaurantId/users/active'
      path: '/users/active'
      fullPath: '/restaurant/$restaurantId/users/active'
      preLoaderRoute: typeof RestaurantRestaurantIdUsersActiveRouteImport
      parentRoute: typeof RestaurantRestaurantIdRoute
    }
    '/restaurant/$restaurantId/menu/edit': {
      id: '/restaurant/$restaurantId/menu/edit'
      path: '/edit'
      fullPath: '/restaurant/$restaurantId/menu/edit'
      preLoaderRoute: typeof RestaurantRestaurantIdMenuEditRouteImport
      parentRoute: typeof RestaurantRestaurantIdMenuRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RestaurantRestaurantIdMenuRouteChildren {
  RestaurantRestaurantIdMenuEditRoute: typeof RestaurantRestaurantIdMenuEditRoute
}

const RestaurantRestaurantIdMenuRouteChildren: RestaurantRestaurantIdMenuRouteChildren =
  {
    RestaurantRestaurantIdMenuEditRoute: RestaurantRestaurantIdMenuEditRoute,
  }

const RestaurantRestaurantIdMenuRouteWithChildren =
  RestaurantRestaurantIdMenuRoute._addFileChildren(
    RestaurantRestaurantIdMenuRouteChildren,
  )

interface RestaurantRestaurantIdRouteChildren {
  RestaurantRestaurantIdMenuRoute: typeof RestaurantRestaurantIdMenuRouteWithChildren
  RestaurantRestaurantIdIndexRoute: typeof RestaurantRestaurantIdIndexRoute
  RestaurantRestaurantIdUsersActiveRoute: typeof RestaurantRestaurantIdUsersActiveRoute
  RestaurantRestaurantIdUsersCreateRoute: typeof RestaurantRestaurantIdUsersCreateRoute
}

const RestaurantRestaurantIdRouteChildren: RestaurantRestaurantIdRouteChildren =
  {
    RestaurantRestaurantIdMenuRoute:
      RestaurantRestaurantIdMenuRouteWithChildren,
    RestaurantRestaurantIdIndexRoute: RestaurantRestaurantIdIndexRoute,
    RestaurantRestaurantIdUsersActiveRoute:
      RestaurantRestaurantIdUsersActiveRoute,
    RestaurantRestaurantIdUsersCreateRoute:
      RestaurantRestaurantIdUsersCreateRoute,
  }

const RestaurantRestaurantIdRouteWithChildren =
  RestaurantRestaurantIdRoute._addFileChildren(
    RestaurantRestaurantIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  RestaurantRestaurantIdRoute: RestaurantRestaurantIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
