/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    isAutoIncrement: true,
                }, email: {
                    name: "email",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                }, role: {
                    name: "role",
                    type: "UserRole",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, posts: {
                    name: "posts",
                    type: "Post",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'author',
                }, emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }, { "name": "@updatedAt", "args": [] }],
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'customer',
                }, members: {
                    name: "members",
                    type: "Member",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, invitations: {
                    name: "invitations",
                    type: "Invitation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'inviter',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        post: {
            name: 'Post', fields: {
                id: {
                    name: "id",
                    type: "Int",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                    isAutoIncrement: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, title: {
                    name: "title",
                    type: "String",
                }, content: {
                    name: "content",
                    type: "String",
                    isOptional: true,
                }, published: {
                    name: "published",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, viewCount: {
                    name: "viewCount",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, author: {
                    name: "author",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'posts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "authorId" },
                }, authorId: {
                    name: "authorId",
                    type: "Int",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'author',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, token: {
                    name: "token",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, userId: {
                    name: "userId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, token: {
                    name: "token",
                    fields: ["token"]
                },
            },
        },
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, accountId: {
                    name: "accountId",
                    type: "String",
                }, providerId: {
                    name: "providerId",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, accessToken: {
                    name: "accessToken",
                    type: "String",
                    isOptional: true,
                }, refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    isOptional: true,
                }, idToken: {
                    name: "idToken",
                    type: "String",
                    isOptional: true,
                }, accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        verification: {
            name: 'Verification', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, identifier: {
                    name: "identifier",
                    type: "String",
                }, value: {
                    name: "value",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }, { "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        organization: {
            name: 'Organization', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                    isOptional: true,
                }, logo: {
                    name: "logo",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, members: {
                    name: "members",
                    type: "Member",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, invitations: {
                    name: "invitations",
                    type: "Invitation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'organization',
                }, restaurant: {
                    name: "restaurant",
                    type: "Restaurant",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'organization',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        member: {
            name: 'Member', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, userId: {
                    name: "userId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'user',
                }, email: {
                    name: "email",
                    type: "String",
                }, role: {
                    name: "role",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'members',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "organizationId" },
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'members',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, organizationId_userId: {
                    name: "organizationId_userId",
                    fields: ["organizationId", "userId"]
                },
            },
        },
        invitation: {
            name: 'Invitation', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, email: {
                    name: "email",
                    type: "String",
                }, role: {
                    name: "role",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, inviterId: {
                    name: "inviterId",
                    type: "Int",
                    isForeignKey: true,
                    relationField: 'inviter',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'invitations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "organizationId" },
                }, inviter: {
                    name: "inviter",
                    type: "User",
                    isDataModel: true,
                    backLink: 'invitations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "inviterId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, organizationId_email: {
                    name: "organizationId_email",
                    fields: ["organizationId", "email"]
                },
            },
        },
        restaurant: {
            name: 'Restaurant', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'organization',
                }, organization: {
                    name: "organization",
                    type: "Organization",
                    isDataModel: true,
                    backLink: 'restaurant',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "organizationId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, address: {
                    name: "address",
                    type: "String",
                    isOptional: true,
                }, phone: {
                    name: "phone",
                    type: "String",
                    isOptional: true,
                }, email: {
                    name: "email",
                    type: "String",
                    isOptional: true,
                }, website: {
                    name: "website",
                    type: "String",
                    isOptional: true,
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, logo: {
                    name: "logo",
                    type: "String",
                    isOptional: true,
                }, timezone: {
                    name: "timezone",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "UTC" }] }],
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "USD" }] }],
                }, isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, settings: {
                    name: "settings",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, categories: {
                    name: "categories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'restaurant',
                }, menuItems: {
                    name: "menuItems",
                    type: "MenuItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'restaurant',
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'restaurant',
                }, vouchers: {
                    name: "vouchers",
                    type: "Voucher",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'restaurant',
                }, plugins: {
                    name: "plugins",
                    type: "Plugin",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'restaurant',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, organizationId: {
                    name: "organizationId",
                    fields: ["organizationId"]
                },
            },
        },
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, restaurantId: {
                    name: "restaurantId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'restaurant',
                }, restaurant: {
                    name: "restaurant",
                    type: "Restaurant",
                    isDataModel: true,
                    backLink: 'categories',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "restaurantId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, sortOrder: {
                    name: "sortOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, parentId: {
                    name: "parentId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'parent',
                }, parent: {
                    name: "parent",
                    type: "Category",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'children',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "parentId" },
                }, children: {
                    name: "children",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'parent',
                }, menuItems: {
                    name: "menuItems",
                    type: "MenuItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        menuItem: {
            name: 'MenuItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, restaurantId: {
                    name: "restaurantId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'restaurant',
                }, restaurant: {
                    name: "restaurant",
                    type: "Restaurant",
                    isDataModel: true,
                    backLink: 'menuItems',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "restaurantId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, price: {
                    name: "price",
                    type: "Float",
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, isAvailable: {
                    name: "isAvailable",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, category: {
                    name: "category",
                    type: "Category",
                    isDataModel: true,
                    backLink: 'menuItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, addons: {
                    name: "addons",
                    type: "MenuItemAddon",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'menuItem',
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'menuItem',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        addonGroup: {
            name: 'AddonGroup', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, selectionType: {
                    name: "selectionType",
                    type: "SelectionType",
                }, isRequired: {
                    name: "isRequired",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, addons: {
                    name: "addons",
                    type: "Addon",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'addonGroup',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        addon: {
            name: 'Addon', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, price: {
                    name: "price",
                    type: "Float",
                }, addonGroupId: {
                    name: "addonGroupId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'addonGroup',
                }, addonGroup: {
                    name: "addonGroup",
                    type: "AddonGroup",
                    isDataModel: true,
                    backLink: 'addons',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "addonGroupId" },
                }, menuItems: {
                    name: "menuItems",
                    type: "MenuItemAddon",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'addon',
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItemAddon",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'addon',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        menuItemAddon: {
            name: 'MenuItemAddon', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, menuItemId: {
                    name: "menuItemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'menuItem',
                }, addonId: {
                    name: "addonId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'addon',
                }, menuItem: {
                    name: "menuItem",
                    type: "MenuItem",
                    isDataModel: true,
                    backLink: 'addons',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "menuItemId" },
                }, addon: {
                    name: "addon",
                    type: "Addon",
                    isDataModel: true,
                    backLink: 'menuItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "addonId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, menuItemId_addonId: {
                    name: "menuItemId_addonId",
                    fields: ["menuItemId", "addonId"]
                },
            },
        },
        order: {
            name: 'Order', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, restaurantId: {
                    name: "restaurantId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'restaurant',
                }, restaurant: {
                    name: "restaurant",
                    type: "Restaurant",
                    isDataModel: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "restaurantId" },
                }, orderNumber: {
                    name: "orderNumber",
                    type: "String",
                }, customerId: {
                    name: "customerId",
                    type: "Int",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'customer',
                }, customer: {
                    name: "customer",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "customerId" },
                }, orderType: {
                    name: "orderType",
                    type: "OrderType",
                }, status: {
                    name: "status",
                    type: "OrderStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, subtotal: {
                    name: "subtotal",
                    type: "Float",
                }, tax: {
                    name: "tax",
                    type: "Float",
                }, discount: {
                    name: "discount",
                    type: "Float",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, total: {
                    name: "total",
                    type: "Float",
                }, paymentStatus: {
                    name: "paymentStatus",
                    type: "PaymentStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, items: {
                    name: "items",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, vouchers: {
                    name: "vouchers",
                    type: "OrderVoucher",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, payments: {
                    name: "payments",
                    type: "Payment",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, orderNumber: {
                    name: "orderNumber",
                    fields: ["orderNumber"]
                },
            },
        },
        orderItem: {
            name: 'OrderItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'items',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, menuItemId: {
                    name: "menuItemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'menuItem',
                }, menuItem: {
                    name: "menuItem",
                    type: "MenuItem",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "menuItemId" },
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, unitPrice: {
                    name: "unitPrice",
                    type: "Float",
                }, totalPrice: {
                    name: "totalPrice",
                    type: "Float",
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, addons: {
                    name: "addons",
                    type: "OrderItemAddon",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'orderItem',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        orderItemAddon: {
            name: 'OrderItemAddon', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderItemId: {
                    name: "orderItemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'orderItem',
                }, addonId: {
                    name: "addonId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'addon',
                }, orderItem: {
                    name: "orderItem",
                    type: "OrderItem",
                    isDataModel: true,
                    backLink: 'addons',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderItemId" },
                }, addon: {
                    name: "addon",
                    type: "Addon",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "addonId" },
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 1 }] }],
                }, unitPrice: {
                    name: "unitPrice",
                    type: "Float",
                }, totalPrice: {
                    name: "totalPrice",
                    type: "Float",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        payment: {
            name: 'Payment', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'payments',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, amount: {
                    name: "amount",
                    type: "Float",
                }, paymentMethod: {
                    name: "paymentMethod",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "PaymentStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, transactionId: {
                    name: "transactionId",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        voucher: {
            name: 'Voucher', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, restaurantId: {
                    name: "restaurantId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'restaurant',
                }, restaurant: {
                    name: "restaurant",
                    type: "Restaurant",
                    isDataModel: true,
                    backLink: 'vouchers',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "restaurantId" },
                }, code: {
                    name: "code",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, discountType: {
                    name: "discountType",
                    type: "DiscountType",
                }, discountValue: {
                    name: "discountValue",
                    type: "Float",
                }, minOrderValue: {
                    name: "minOrderValue",
                    type: "Float",
                    isOptional: true,
                }, maxDiscount: {
                    name: "maxDiscount",
                    type: "Float",
                    isOptional: true,
                }, usageLimit: {
                    name: "usageLimit",
                    type: "Int",
                    isOptional: true,
                }, usedCount: {
                    name: "usedCount",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, isActive: {
                    name: "isActive",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, validFrom: {
                    name: "validFrom",
                    type: "DateTime",
                }, validUntil: {
                    name: "validUntil",
                    type: "DateTime",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, orders: {
                    name: "orders",
                    type: "OrderVoucher",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'voucher',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            },
        },
        orderVoucher: {
            name: 'OrderVoucher', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, voucherId: {
                    name: "voucherId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'voucher',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'vouchers',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, voucher: {
                    name: "voucher",
                    type: "Voucher",
                    isDataModel: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "voucherId" },
                }, discount: {
                    name: "discount",
                    type: "Float",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, orderId_voucherId: {
                    name: "orderId_voucherId",
                    fields: ["orderId", "voucherId"]
                },
            },
        },
        plugin: {
            name: 'Plugin', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, restaurantId: {
                    name: "restaurantId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'restaurant',
                }, restaurant: {
                    name: "restaurant",
                    type: "Restaurant",
                    isDataModel: true,
                    backLink: 'plugins',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "restaurantId" },
                }, name: {
                    name: "name",
                    type: "String",
                }, version: {
                    name: "version",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, isEnabled: {
                    name: "isEnabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, config: {
                    name: "config",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, restaurantId_name: {
                    name: "restaurantId_name",
                    fields: ["restaurantId", "name"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['Session', 'Account', 'Member', 'Invitation'],
        organization: ['Member', 'Invitation', 'Restaurant'],
        restaurant: ['Category', 'MenuItem', 'Order', 'Voucher', 'Plugin'],

    },
    authModel: 'User'

};
export default metadata;
